<template>
  <div>
    <v-container>
      <v-tabs v-model="currentTab">
        <v-tab tab-value="general">General</v-tab>
        <v-tab tab-value="connect-app">Connect ChatGPT</v-tab>
        <v-tab tab-value="api-keys"
          >User API Keys
          <v-chip class="ml-2" small color="warning">Legacy</v-chip></v-tab
        >
        <v-tab tab-value="db-settings">Database </v-tab>
      </v-tabs>

      <div v-if="currentTab == 'general'">
        <div class="my-4">
          Add the following script to your <code>index.html</code> page, and you
          will see a chatbot pop up on your site.
        </div>
        --- script start ---
        <div class="my-4">
          <code> src="https://scraper.ai/chatpanel.js" </code>
          <div>
            <code>id="chatPanelScript"</code>
          </div>
          <div>
            <code>
              data-api-key="{{ currentLoggedInUser.apiKey || "your-api-key" }}
            </code>
          </div>
        </div>
        --- script end ---
      </div>
      <div v-if="currentTab == 'connect-app'">
        <div class="my-4">
          <div>
            <strong>Connect ChatGPT </strong>
            <v-chip
              small
              v-if="currentLoggedInUser.chatgptApiKey"
              color="success"
              >connected</v-chip
            >
          </div>
          <div>
            Connect your openai for we to process your chatbot, remember all the
            chats will be handled by this account
          </div>
          <div v-if="currentLoggedInUser.chatgptApiKey" class="my-4">
            <v-btn
              color="success"
              @click="connectChatGptDialog = true"
              depressed
              class="mr-2"
              outlined
              >Edit</v-btn
            >
            <v-btn
              color="error"
              @click="connectChatGptDialog = true"
              depressed
              class="mr-2"
              outlined
              >Disconnect</v-btn
            >

            <v-switch
              @change="updateChatGptStatus"
              v-model="chatgptEnabled"
              :label="`Automated response generated by ChatGPT without any human intervention.`"
            ></v-switch>
          </div>
          <div v-else>
            <v-btn @click="connectChatGptDialog = true" depressed class="my-2"
              >Connect</v-btn
            >
          </div>
        </div>
      </div>
      <div v-if="currentTab == 'api-keys'">
        <v-alert outlined type="info">
          Your secret key will be disabled until the payment is made or the
          billing cycle lapses. Once we receive the payment, the key will be
          reactivated and function normally.
        </v-alert>
        <div>
          Do not share your API key with others, or expose it in the browser or
          other client-side code. In order to protect the security of your
          account, scraperAI may also automatically disable any API key that has
          leaked publicly.
        </div>

        <div class="my-5">
          SECRET KEY - <code>{{ currentLoggedInUser.apiKey }}</code>
        </div>
      </div>
      <div v-if="currentTab == 'db-settings'">
        <div class="my-4">
          <div>
            <strong>Connect DB </strong>
            <v-chip small v-if="currentLoggedInUser.dbUri" color="success"
              >connected</v-chip
            >
          </div>
          <div>
            Connect your db for we to process your chatbot, remember all the
            chats will be stored in this db, if db fails, it will be stored in
            our db.
          </div>
          <div v-if="currentLoggedInUser.dbUri" class="my-4">
            <v-btn
              color="success"
              @click="connectDBDialog = true"
              depressed
              class="mr-2"
              outlined
              >Edit</v-btn
            >
            <v-btn
              :disabled="loading"
              @click="removeDbUri"
              class="my-4 mr-2"
              depressed
              color="error"
              >Remove</v-btn
            >
          </div>
          <div v-else>
            <v-btn @click="connectDBDialog = true" depressed class="my-2"
              >Connect</v-btn
            >
          </div>
        </div>
      </div>
    </v-container>
    <v-dialog max-width="400" v-model="connectChatGptDialog">
      <v-card :loading="loading">
        <v-container>
          <div class="my-4">
            <div><strong>API Key </strong></div>
            <div>
              Your chatgpt api key, don't worry we will make sure its not
              misused
            </div>
            <v-text-field
              hide-details="auto"
              dense
              v-model="chatgptApiKey"
              outlined
              style="max-width: 600px"
            ></v-text-field>
          </div>
          <div class="my-4">
            <div><strong>Model </strong></div>
            <div>
              Your chatgpt model key, don't worry we will make sure its not
              misused
            </div>
            <v-select
              hide-details="auto"
              dense
              v-model="chatgptModel"
              outlined
              :items="chatGptModels"
              style="max-width: 600px"
            ></v-select>
          </div>

          <div class="my-4">
            <div><strong>Content </strong></div>
            <div>Text related to you business (Do not change this)</div>
            <v-textarea
              readonly
              hide-details="auto"
              dense
              v-model="chatgptContentPrompt"
              outlined
              style="max-width: 600px"
            ></v-textarea>
          </div>
          <v-btn
            :disabled="loading"
            @click="updateChatGptSettings"
            class="my-4"
            depressed
            color="primary"
            >Continue</v-btn
          >
        </v-container>
      </v-card>
    </v-dialog>
    <v-dialog max-width="400" v-model="connectDBDialog">
      <v-card :loading="loading">
        <v-container>
          <div class="my-4">
            <div><strong>DB URI </strong></div>
            <div>Enter your Mongodb URI for us to connect.</div>
            <v-text-field
              hide-details="auto"
              dense
              v-model="dbUri"
              outlined
              style="max-width: 600px"
            ></v-text-field>
          </div>
          <div class="my-4">
            <div><strong>Database </strong></div>
            <div>
              Your chatgpt model key, don't worry we will make sure its not
              misused
            </div>
            <v-select
              hide-details="auto"
              dense
              v-model="selectedDbModel"
              outlined
              :items="dbModels"
              style="max-width: 600px"
            ></v-select>
          </div>

          <v-btn
            :disabled="loading"
            @click="updateDBSettings"
            class="my-4"
            depressed
            color="primary"
            >Continue</v-btn
          >
        </v-container>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
import apiClient from "@/service/axios";
export default {
  data() {
    return {
      loading: false,
      chatgptEnabled: false,
      currentTab: "general",
      currentLoggedInUser: "",
      connectChatGptDialog: false,
      chatgptApiKey: "",
      chatGptModels: [
        "gpt-1",
        "gpt-2",
        "gpt-3",
        "gpt-3.5",
        "gpt-3.5-turbo",
        "gpt-4",
        "gpt-4-turbo",
        "gpt-4o-mini",
      ],
      chatgptModel: "gpt-3.5-turbo",
      chatgptContentPrompt:
        "You are a friendly and helpful customer support assistant. Provide concise answers in a conversational tone. Keep the responses very short (1-2 sentences), informative, and easy to read, as if chatting with a human. return in html if required",
      dbUri: "",
      dbModels: ["Mongodb"],
      selectedDbModel: "Mongodb",
      connectDBDialog: false,
    };
  },
  mounted() {
    this.currentLoggedInUserInfo();
  },
  methods: {
    removeDbUri() {
      if (confirm("Are you sure you want to remove?")) {
        this.dbUri = null;
        this.updateDBSettings();
      }
    },
    async currentLoggedInUserInfo() {
      try {
        const { data } = await apiClient.get("/clients/currentUser");
        this.currentLoggedInUser = data;
        this.chatgptApiKey = data.chatgptApiKey;
        this.chatgptModel = data.chatGptModel;
        this.chatgptContentPrompt = data.chatgptContentPrompt;
        this.chatgptEnabled = data.chatgptEnabled;
        this.dbUri = data.dbUri;
      } catch {
        console.log("something is wrong");
      }
    },
    async updateChatGptStatus() {
      try {
        this.loading = true;
        const { data } = await apiClient.post("/clients/settings/chatgpt", {
          chatgptEnabled: this.chatgptEnabled,
        });
        this.currentLoggedInUser = data;
        this.loading = false;
      } catch (error) {
        console.log("🚀 ~ updateChatGptSettings ~ error:", error);
        this.loading = false;
        console.log("something is wrong");
      }
    },
    async updateChatGptSettings() {
      try {
        this.loading = true;
        const { data } = await apiClient.post("/clients/settings/chatgpt", {
          chatgptApiKey: this.chatgptApiKey,
          chatGptModel: this.chatgptModel,
          chatgptContentPrompt: this.chatgptContentPrompt,
        });
        this.currentLoggedInUser = data;
        this.loading = false;
        this.connectChatGptDialog = false;
      } catch (error) {
        console.log("🚀 ~ updateChatGptSettings ~ error:", error);
        this.loading = false;
        console.log("something is wrong");
      }
    },
    async updateDBSettings() {
      try {
        this.loading = true;
        const { data } = await apiClient.post("/clients/settings/db", {
          dbUri: this.dbUri,
        });
        this.currentLoggedInUser = data;
        this.loading = false;
        this.connectDBDialog = false;
      } catch (error) {
        this.loading = false;
        console.log("something is wrong");
      }
    },
  },
};
</script>

<style></style>
