// Lucide icons for Vuetify. Use them as `$name` with the Lucide icon name,
// e.g. <v-icon>$search</v-icon> or prepend-inner-icon="$search". To add one,
// import it from "lucide" and add it to APP_ICONS. Vuetify's own icons
// (checkboxes, dropdowns, alerts...) are remapped in VUETIFY_ICONS.
import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeAlert,
  BookOpen,
  Bot,
  Braces,
  Brain,
  Building2,
  ChartArea,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartSpline,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleUser,
  CircleX,
  Clock,
  Code,
  Copy,
  Crown,
  Database,
  DatabaseZap,
  Dot,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Files,
  Flame,
  FlaskConical,
  FolderTree,
  Funnel,
  Globe,
  GlobeLock,
  Headphones,
  Headset,
  History,
  Info,
  Key,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  ListChecks,
  LoaderCircle,
  Lock,
  MapPin,
  Menu,
  MessageCircle,
  MessageCircleMore,
  MessageCircleWarning,
  MessageCircleX,
  MessageSquare,
  MessageSquareCheck,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Minus,
  Monitor,
  Network,
  OctagonAlert,
  Paperclip,
  Pencil,
  Phone,
  PhoneCall,
  Play,
  Plug,
  Plus,
  Puzzle,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  RotateCcwKey,
  Route,
  Search,
  Send,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldPlus,
  ShieldUser,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  SquareMinus,
  Star,
  StarHalf,
  Store,
  Tag,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Unlink,
  User,
  UserCheck,
  UserCog,
  UserLock,
  UserMinus,
  UserPlus,
  UserSearch,
  UserX,
  Users,
  WandSparkles,
  Webhook,
  X,
  Zap,
  Activity,
  Folder,
  FolderOpen,
  NotebookPen,
  Upload,
  Pause,
  Archive,
  Layers,
  FileUp,
  MessageCircleQuestionMark,
  ThumbsUp,
  Scale,
  GitCompare,
  CheckCheck,
} from "lucide";
import * as brands from "@/icons/brands";

const SVG_ATTRS = {
  xmlns: "http://www.w3.org/2000/svg",
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  "stroke-width": 2,
  "stroke-linecap": "round",
  "stroke-linejoin": "round",
  "aria-hidden": "true",
};
const FILLED_ATTRS = { fill: "currentColor", stroke: "none" };

// Renders a Lucide icon node ([tag, attrs] pairs) as an inline SVG. Vuetify
// sizes it through the v-icon__component class and colours it via currentColor.
const LucideIcon = {
  name: "LucideIcon",
  functional: true,
  props: {
    node: { type: Array, required: true },
    filled: { type: Boolean, default: false },
  },
  render(h, { props, data }) {
    return h(
      "svg",
      {
        ...data,
        attrs: { ...SVG_ATTRS, ...(props.filled ? FILLED_ATTRS : {}), ...data.attrs },
      },
      props.node.map(([tag, attrs]) => h(tag, { attrs })),
    );
  },
};

const APP_ICONS = {
  "star": Star,
  "check-check": CheckCheck,
  "git-compare": GitCompare,
  "scale": Scale,
  "thumbs-up": ThumbsUp,
  "message-circle-question-mark": MessageCircleQuestionMark,
  "file-up": FileUp,
  "loader-circle": LoaderCircle,
  "layers": Layers,
  "archive": Archive,
  "pause": Pause,
  "upload": Upload,
  "notebook-pen": NotebookPen,
  "folder-open": FolderOpen,
  "folder": Folder,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "badge-alert": BadgeAlert,
  "book-open": BookOpen,
  "bot": Bot,
  "braces": Braces,
  "brain": Brain,
  "building-2": Building2,
  "chart-area": ChartArea,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "chart-spline": ChartSpline,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "circle-user": CircleUser,
  "clock": Clock,
  "code": Code,
  "copy": Copy,
  "crown": Crown,
  "database": Database,
  "database-zap": DatabaseZap,
  "dot": Dot,
  "download": Download,
  "ellipsis": Ellipsis,
  "ellipsis-vertical": EllipsisVertical,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "file-json": FileJson,
  "file-search": FileSearch,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "files": Files,
  "flame": Flame,
  "flask-conical": FlaskConical,
  "folder-tree": FolderTree,
  "funnel": Funnel,
  "globe": Globe,
  "globe-lock": GlobeLock,
  "headphones": Headphones,
  "headset": Headset,
  "history": History,
  "info": Info,
  "key": Key,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "lightbulb": Lightbulb,
  "link": Link,
  "list": List,
  "list-checks": ListChecks,
  "lock": Lock,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-circle-more": MessageCircleMore,
  "message-circle-warning": MessageCircleWarning,
  "message-circle-x": MessageCircleX,
  "message-square": MessageSquare,
  "message-square-check": MessageSquareCheck,
  "message-square-text": MessageSquareText,
  "messages-square": MessagesSquare,
  "mic": Mic,
  "monitor": Monitor,
  "network": Network,
  "octagon-alert": OctagonAlert,
  "pencil": Pencil,
  "phone": Phone,
  "phone-call": PhoneCall,
  "play": Play,
  "plug": Plug,
  "plus": Plus,
  "puzzle": Puzzle,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rocket": Rocket,
  "rotate-ccw": RotateCcw,
  "rotate-ccw-key": RotateCcwKey,
  "route": Route,
  "search": Search,
  "send": Send,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  "shield-plus": ShieldPlus,
  "shield-user": ShieldUser,
  "smartphone": Smartphone,
  "sparkles": Sparkles,
  "store": Store,
  "tag": Tag,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "unlink": Unlink,
  "user": User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-lock": UserLock,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-search": UserSearch,
  "user-x": UserX,
  "users": Users,
  "wand-sparkles": WandSparkles,
  "webhook": Webhook,
  "x": X,
  "zap": Zap,
  "activity": Activity,
};

const VUETIFY_ICONS = {
  complete: Check,
  cancel: CircleX,
  close: X,
  delete: CircleX,
  clear: X,
  success: CircleCheck,
  info: Info,
  warning: TriangleAlert,
  error: CircleAlert,
  prev: ChevronLeft,
  next: ChevronRight,
  checkboxOn: SquareCheck,
  checkboxOff: Square,
  checkboxIndeterminate: SquareMinus,
  delimiter: Circle,
  sort: ArrowUp,
  expand: ChevronDown,
  menu: Menu,
  subgroup: ChevronDown,
  dropdown: ChevronDown,
  radioOn: CircleDot,
  radioOff: Circle,
  edit: Pencil,
  ratingEmpty: Star,
  ratingFull: Star,
  ratingHalf: StarHalf,
  loading: LoaderCircle,
  first: ChevronsLeft,
  last: ChevronsRight,
  unfold: ChevronsUpDown,
  file: Paperclip,
  plus: Plus,
  minus: Minus,
};

const entry = (node, filled = false) => ({ component: LucideIcon, props: { node, filled } });

export const iconValues = {
  ...Object.fromEntries(Object.entries(APP_ICONS).map(([k, node]) => [k, entry(node)])),
  ...Object.fromEntries(
    Object.entries(brands).map(([k, { node, filled }]) => [k, entry(node, filled)]),
  ),
  ...Object.fromEntries(Object.entries(VUETIFY_ICONS).map(([k, node]) => [k, entry(node)])),
};
